nome: Gerar dados

em:
  Horário: #Executar a cada 12 horas
    - cron: "* */12 * * * *"
  workflow_dispatch:

Vagas:
  construir:
    name: Trabalhos para atualizar dados
    Runs-on: ubuntu-mais recente
    Passos:
      #snake Animação
      - usos: Platane/snk@master
        Identificação: Cobra-GIF
        com:
          github_user_name: acssilva
          svg_out_path: dist/github-contribuition-grid-snake.svg

      - Usos: Crazy-Max/Ghaction-GitHub-pages@v2.1.3
        com:
            target_branch: saída
            build_dir: dist
        env:
          GITHUB_TOKEN: ${{ segredos. GITHUB_TOKEN }}
